import pickle



try:
	with open('config.bin', 'rb') as f:
		data = f.read()
		WIDTH = data[0]
		HEIGHT = data[1]
		f.close()
except:
	WIDTH = 800
	HEIGHT = 800


OBJECT_MULTIPLYER_WIDTH = WIDTH // 400
OBJECT_MULTIPLYER_HEIGHT = HEIGHT // 400
AVERAGE_MULTIPLYER = (OBJECT_MULTIPLYER_WIDTH + OBJECT_MULTIPLYER_HEIGHT) // 2

FPS = 60

START_BUTTON_SIZE = (165*OBJECT_MULTIPLYER_WIDTH, 75*OBJECT_MULTIPLYER_HEIGHT)
BLOCK_SIZE = (25*OBJECT_MULTIPLYER_WIDTH, 25*OBJECT_MULTIPLYER_HEIGHT)
TANK_SIZE = (15*OBJECT_MULTIPLYER_WIDTH, 15*OBJECT_MULTIPLYER_HEIGHT)
SHOT_SIZE = (8*OBJECT_MULTIPLYER_WIDTH, 8*OBJECT_MULTIPLYER_HEIGHT)

BULLET_SPEED = 7
TANK_SPEED = 2